# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy to Azure Web App - DevToolz

on:
  push:
    branches:
      - deploy-branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_684079238713433EAC39C50F0365A2DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B10616B4C66441C8B4287EDF832A23B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C8B92E609C4D4823B39DEEFC7C599643 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DevToolz'
          slot-name: 'Production'
          package: .