name: Deploy ASP.Net Core app to Azure Web App - DevToolz

on:
  push:
    branches:
      - deploy-branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Necessário para solicitar o JWT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3F1004E6C28743398F66C4D216A5F89F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E40B7F0764B7422783B0438339C55217 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E1EC133B00F7476081A079FB00DFA2BB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "DevToolz"
          slot-name: "Production"
          package: .
