name: Build and Deploy .NET

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -R

      - name: Check if project file exists
        run: |
          if [ ! -f "./DevToolz/DevToolz.sln" ]; then
            echo "Project file not found!"
            exit 1
          else
            echo "Project file found."
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
        
      - name: Restore dependencies
        run: dotnet restore ./DevToolz/DevToolz.sln
      
      - name: Build
        run: dotnet build ./DevToolz/DevToolz.sln --configuration Release

      - name: Create publish directory
        run: mkdir -p ./publish

      - name: Publish
        run: dotnet publish ./DevToolz/DevToolz.sln --configuration Release --output ./publish

      - name: Create deploy branch if it doesn't exist
        run: |
          git checkout -b deploy-branch || true
          git push origin deploy-branch

      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy-branch 

      - name: Copy files to deploy branch
        run: |
          cp -r ./publish/* ./
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy updated build"
          git push origin deploy-branch
