name: Deploy to Azure

on:
  push:
    branches:
      - main # Ou a branch que você utiliza para deploy
  pull_request:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0' # Ou a versão do .NET que você está usando

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the .NET application
        run: dotnet publish --configuration Release --output ./publish

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ou a versão do Node.js que você está usando

      - name: Install Angular dependencies
        run: npm install
        working-directory: ./ClientApp # Caminho para a pasta do Angular

      - name: Build Angular application
        run: npm run build --prod
        working-directory: ./ClientApp # Caminho para a pasta do Angular

      - name: Prepare Angular build for .NET
        run: |
          mkdir -p ./publish/wwwroot
          cp -r ./ClientApp/dist/* ./publish/wwwroot/

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-app-service-name' # Nome do serviço na Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
