name: Build and Deploy .NET

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
        
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: cd DevToolz && dotnet build --configuration Release

      - name: Publish
        run: cd DevToolz && dotnet publish --configuration Release --output ./publish

      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy-branch 

      - name: Copy files to deploy branch
        run: |
          cp -r ./publish/* ./
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy updated build"
          git push origin deploy-branch
