name: Deploy Web API .NET to Deploy Branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish-web-api:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x" # Especifique a versão do .NET usada

      - name: Publicar Web API
        run: dotnet publish ./DevToolz/DevToolz.sln -c Release -o ./output

  deploy-to-service:
    name: Deploy para Serviço
    needs: publish-web-api
    runs-on: ubuntu-latest

    steps:
      - name: Avisar que funcionou
        run: echo 'Deu certo!'
