name: Deploy Web API .NET to Deploy Branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish-web-api:
    name: Publicação da Web API
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x" # Especifique a versão do .NET usada

      - name: Publicar Web API
        run: dotnet publish ./DevToolz/DevToolz.sln -c Release -o ./output --self-contained

      - name: Guardar arquivos
        uses: actions/upload-artifact@v4
        with:
          name: web-api-artifacts
          path: |
            ./output
            !./output/*.pdb
            !./output/appsettings.Development.json
          retention-days: 5
          
  deploy-to-local:
    name: Deploy para local
    needs: publish-web-api
    runs-on: ubuntu-latest

    steps:
      - name: Trocar para o branch local-deploy-branch
        uses: actions/checkout@v4
        with:
          ref: local-deploy-branch
          
      - name: Download dos arquivos publicados
        uses: actions/download-artifact@v4
        with:
          name: web-api-artifacts
          
      - name: Avisar que funcionou
        run: echo 'Deu certo!'
