name: Deploy Web API .NET to Deploy Branch

on:
  push:
    branches:
      - main # Mude para o branch que você deseja monitorar para o deploy
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x" # Especifique a versão do .NET usada

      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.nuget\packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: |
            **\bin
            **\obj
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Publish Web API
        run: dotnet publish -c Release -o ./output

      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          ref: deploy-branch # Altere para o nome do branch de destino

      - name: Copy published files to deploy branch
        run: |
          robocopy ./output ./ /E /MIR

      - name: Commit and push changes
        run: |
          git config --global user.name 'LucasZottis'
          git add -A
          git commit -m "Update published files"
          git push origin deploy-branch
